# https://travis-ci.org/tornadoweb/tornado

dist: xenial
language: python
addons:
  apt:
    packages:
      - libgnutls-dev

# For a list of available versions,run
#     aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
jobs:
  fast_finish: true
  include:
    # 3.5.2 is interesting because it's the version in ubuntu 16.04, and due to python's
    # "provisional feature" rules there are significant differences between patch
    # versions for asyncio and typing.
    - python: 3.5.2
      # Twisted doesn't install on python 3.5.2, so don't run the "full" tests.
      env: TOX_ENV=py35
    - python: '3.5'
      services: docker
      env: TOX_ENV=py35-full BUILD_WHEEL=1 CIBW_BUILD=cp35-manylinux_x86_64
    - python: '3.5'
      arch: arm64
      services: docker
      env: TOX_ENV=py35-full BUILD_WHEEL=1 CIBW_BUILD=cp35-manylinux_aarch64
    - python: '3.6'
      services: docker
      env: TOX_ENV=py36-full BUILD_WHEEL=1 CIBW_BUILD=cp36-manylinux_x86_64
    - python: '3.6'
      arch: arm64
      services: docker
      env: TOX_ENV=py36-full BUILD_WHEEL=1 CIBW_BUILD=cp36-manylinux_aarch64
    - python: '3.7'
      services: docker
      env: TOX_ENV=py37-full BUILD_WHEEL=1 CIBW_BUILD=cp37-manylinux_x86_64
    - python: '3.7'
      arch: arm64
      services: docker
      env: TOX_ENV=py37-full BUILD_WHEEL=1 CIBW_BUILD=cp37-manylinux_aarch64
    - python: '3.8'
      services: docker
      env: TOX_ENV=py38-full BUILD_WHEEL=1 CIBW_BUILD=cp38-manylinux_x86_64
    - python: '3.8'
      arch: arm64
      services: docker
      env: TOX_ENV=py38-full BUILD_WHEEL=1 CIBW_BUILD=cp38-manylinux_aarch64
    - python: pypy3.5-5.10.1
      # Pypy is a lot slower due to jit warmup costs, so don't run the "full"
      # test config there.
      env: TOX_ENV=pypy3
    - python: nightly
      env: TOX_ENV=py3-full
      # Docs and lint python versions must be synced with those in tox.ini
    - python: '3.8'
      env: TOX_ENV=docs
    - python: '3.8'
      arch: arm64
      env: TOX_ENV=docs
    - python: '3.8'
      env: TOX_ENV=lint
  allow_failures:
    # Currently failing due to https://foss.heptapod.net/pypy/cffi/issues/458
    - python: nightly

install:
    - travis_retry pip install tox
    - python -VV
    - curl-config --version; pip freeze

script:
    - |
      #Skipping the tests for which we have already tested using it's own built wheel@@@@@@@@@@@@@ 
      if [[ -z ${BUILD_WHEEL} ]]; then
         tox -e $TOX_ENV -- $TOX_ARGS
      else
         pip install -U cibuildwheel
         cibuildwheel --output-dir dist
         sudo rm -rf dist/*manylinux2010_x86_64.whl
         tox --installpkg dist/*.whl -e $TOX_ENV -- $TOX_ARGS
      fi
